kind: pipeline
name: default
workspace:
  base: /go
  path: src/codeberg.org/momar/badboys
steps:
- name: build
  image: golang
  commands:
  - go get
  - CGO_ENABLED=0 GOOS=linux go build -a -v -tags netgo -o badboys .
#- name: test
#  image: busybox
#  commands:
#  - echo 
#  - /go/src/codeberg.org/momar/badboys/badboys
- name: publish
  image: plugins/s3
  settings:
    endpoint: https://minio.mo-mar.de
    bucket: get
    source: /go/src/codeberg.org/momar/badboys/badboys
    target: /
    access_key:
      from_secret: access_key
    secret_key:
      from_secret: secret_key
#- name: release
